# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.6)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.20)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget SUNDIALS::core_static SUNDIALS::core_shared SUNDIALS::nvecserial_static SUNDIALS::nvecserial_shared SUNDIALS::nvecmanyvector_static SUNDIALS::nvecmanyvector_shared SUNDIALS::sunmatrixband_static SUNDIALS::sunmatrixband_shared SUNDIALS::sunmatrixdense_static SUNDIALS::sunmatrixdense_shared SUNDIALS::sunmatrixsparse_static SUNDIALS::sunmatrixsparse_shared SUNDIALS::sunlinsolband_static SUNDIALS::sunlinsolband_shared SUNDIALS::sunlinsoldense_static SUNDIALS::sunlinsoldense_shared SUNDIALS::sunlinsolpcg_static SUNDIALS::sunlinsolpcg_shared SUNDIALS::sunlinsolspbcgs_static SUNDIALS::sunlinsolspbcgs_shared SUNDIALS::sunlinsolspfgmr_static SUNDIALS::sunlinsolspfgmr_shared SUNDIALS::sunlinsolspgmr_static SUNDIALS::sunlinsolspgmr_shared SUNDIALS::sunlinsolsptfqmr_static SUNDIALS::sunlinsolsptfqmr_shared SUNDIALS::sunnonlinsolnewton_static SUNDIALS::sunnonlinsolnewton_shared SUNDIALS::sunnonlinsolfixedpoint_static SUNDIALS::sunnonlinsolfixedpoint_shared SUNDIALS::cvode_static SUNDIALS::cvode_shared)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target SUNDIALS::core_static
add_library(SUNDIALS::core_static STATIC IMPORTED)

set_target_properties(SUNDIALS::core_static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "SUNDIALS_STATIC_DEFINE"
  INTERFACE_INCLUDE_DIRECTORIES "/home/borja/sundials/cvode-7.2.1/include;/home/borja/sundials/instdir/include;/home/borja/sundials/cvode-7.2.1/src/sundials;/home/borja/sundials/instdir/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>"
)

# Create imported target SUNDIALS::core_shared
add_library(SUNDIALS::core_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::core_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/borja/sundials/cvode-7.2.1/include;/home/borja/sundials/instdir/include;/home/borja/sundials/cvode-7.2.1/src/sundials;/home/borja/sundials/instdir/src/sundials"
)

# Create imported target SUNDIALS::nvecserial_static
add_library(SUNDIALS::nvecserial_static STATIC IMPORTED)

set_target_properties(SUNDIALS::nvecserial_static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "SUNDIALS_STATIC_DEFINE"
  INTERFACE_INCLUDE_DIRECTORIES "/home/borja/sundials/cvode-7.2.1/include;/home/borja/sundials/instdir/include;/home/borja/sundials/cvode-7.2.1/src/sundials;/home/borja/sundials/instdir/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::nvecserial_shared
add_library(SUNDIALS::nvecserial_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::nvecserial_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/borja/sundials/cvode-7.2.1/include;/home/borja/sundials/instdir/include;/home/borja/sundials/cvode-7.2.1/src/sundials;/home/borja/sundials/instdir/src/sundials"
  INTERFACE_LINK_LIBRARIES "SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::nvecmanyvector_static
add_library(SUNDIALS::nvecmanyvector_static STATIC IMPORTED)

set_target_properties(SUNDIALS::nvecmanyvector_static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "SUNDIALS_STATIC_DEFINE"
  INTERFACE_INCLUDE_DIRECTORIES "/home/borja/sundials/cvode-7.2.1/include;/home/borja/sundials/instdir/include;/home/borja/sundials/cvode-7.2.1/src/sundials;/home/borja/sundials/instdir/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::nvecmanyvector_shared
add_library(SUNDIALS::nvecmanyvector_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::nvecmanyvector_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/borja/sundials/cvode-7.2.1/include;/home/borja/sundials/instdir/include;/home/borja/sundials/cvode-7.2.1/src/sundials;/home/borja/sundials/instdir/src/sundials"
  INTERFACE_LINK_LIBRARIES "SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::sunmatrixband_static
add_library(SUNDIALS::sunmatrixband_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunmatrixband_static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "SUNDIALS_STATIC_DEFINE"
  INTERFACE_INCLUDE_DIRECTORIES "/home/borja/sundials/cvode-7.2.1/include;/home/borja/sundials/instdir/include;/home/borja/sundials/cvode-7.2.1/src/sundials;/home/borja/sundials/instdir/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::sunmatrixband_shared
add_library(SUNDIALS::sunmatrixband_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::sunmatrixband_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/borja/sundials/cvode-7.2.1/include;/home/borja/sundials/instdir/include;/home/borja/sundials/cvode-7.2.1/src/sundials;/home/borja/sundials/instdir/src/sundials"
  INTERFACE_LINK_LIBRARIES "SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::sunmatrixdense_static
add_library(SUNDIALS::sunmatrixdense_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunmatrixdense_static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "SUNDIALS_STATIC_DEFINE"
  INTERFACE_INCLUDE_DIRECTORIES "/home/borja/sundials/cvode-7.2.1/include;/home/borja/sundials/instdir/include;/home/borja/sundials/cvode-7.2.1/src/sundials;/home/borja/sundials/instdir/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::sunmatrixdense_shared
add_library(SUNDIALS::sunmatrixdense_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::sunmatrixdense_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/borja/sundials/cvode-7.2.1/include;/home/borja/sundials/instdir/include;/home/borja/sundials/cvode-7.2.1/src/sundials;/home/borja/sundials/instdir/src/sundials"
  INTERFACE_LINK_LIBRARIES "SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::sunmatrixsparse_static
add_library(SUNDIALS::sunmatrixsparse_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunmatrixsparse_static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "SUNDIALS_STATIC_DEFINE"
  INTERFACE_INCLUDE_DIRECTORIES "/home/borja/sundials/cvode-7.2.1/include;/home/borja/sundials/instdir/include;/home/borja/sundials/cvode-7.2.1/src/sundials;/home/borja/sundials/instdir/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::sunmatrixsparse_shared
add_library(SUNDIALS::sunmatrixsparse_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::sunmatrixsparse_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/borja/sundials/cvode-7.2.1/include;/home/borja/sundials/instdir/include;/home/borja/sundials/cvode-7.2.1/src/sundials;/home/borja/sundials/instdir/src/sundials"
  INTERFACE_LINK_LIBRARIES "SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::sunlinsolband_static
add_library(SUNDIALS::sunlinsolband_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunlinsolband_static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "SUNDIALS_STATIC_DEFINE"
  INTERFACE_INCLUDE_DIRECTORIES "/home/borja/sundials/cvode-7.2.1/include;/home/borja/sundials/instdir/include;/home/borja/sundials/cvode-7.2.1/src/sundials;/home/borja/sundials/instdir/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_shared;SUNDIALS::sunmatrixband_shared"
)

# Create imported target SUNDIALS::sunlinsolband_shared
add_library(SUNDIALS::sunlinsolband_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::sunlinsolband_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/borja/sundials/cvode-7.2.1/include;/home/borja/sundials/instdir/include;/home/borja/sundials/cvode-7.2.1/src/sundials;/home/borja/sundials/instdir/src/sundials"
  INTERFACE_LINK_LIBRARIES "SUNDIALS::core_shared;SUNDIALS::sunmatrixband_shared"
)

# Create imported target SUNDIALS::sunlinsoldense_static
add_library(SUNDIALS::sunlinsoldense_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunlinsoldense_static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "SUNDIALS_STATIC_DEFINE"
  INTERFACE_INCLUDE_DIRECTORIES "/home/borja/sundials/cvode-7.2.1/include;/home/borja/sundials/instdir/include;/home/borja/sundials/cvode-7.2.1/src/sundials;/home/borja/sundials/instdir/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_shared;SUNDIALS::sunmatrixdense_shared"
)

# Create imported target SUNDIALS::sunlinsoldense_shared
add_library(SUNDIALS::sunlinsoldense_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::sunlinsoldense_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/borja/sundials/cvode-7.2.1/include;/home/borja/sundials/instdir/include;/home/borja/sundials/cvode-7.2.1/src/sundials;/home/borja/sundials/instdir/src/sundials"
  INTERFACE_LINK_LIBRARIES "SUNDIALS::core_shared;SUNDIALS::sunmatrixdense_shared"
)

# Create imported target SUNDIALS::sunlinsolpcg_static
add_library(SUNDIALS::sunlinsolpcg_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunlinsolpcg_static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "SUNDIALS_STATIC_DEFINE"
  INTERFACE_INCLUDE_DIRECTORIES "/home/borja/sundials/cvode-7.2.1/include;/home/borja/sundials/instdir/include;/home/borja/sundials/cvode-7.2.1/src/sundials;/home/borja/sundials/instdir/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::sunlinsolpcg_shared
add_library(SUNDIALS::sunlinsolpcg_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::sunlinsolpcg_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/borja/sundials/cvode-7.2.1/include;/home/borja/sundials/instdir/include;/home/borja/sundials/cvode-7.2.1/src/sundials;/home/borja/sundials/instdir/src/sundials"
  INTERFACE_LINK_LIBRARIES "SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::sunlinsolspbcgs_static
add_library(SUNDIALS::sunlinsolspbcgs_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunlinsolspbcgs_static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "SUNDIALS_STATIC_DEFINE"
  INTERFACE_INCLUDE_DIRECTORIES "/home/borja/sundials/cvode-7.2.1/include;/home/borja/sundials/instdir/include;/home/borja/sundials/cvode-7.2.1/src/sundials;/home/borja/sundials/instdir/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::sunlinsolspbcgs_shared
add_library(SUNDIALS::sunlinsolspbcgs_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::sunlinsolspbcgs_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/borja/sundials/cvode-7.2.1/include;/home/borja/sundials/instdir/include;/home/borja/sundials/cvode-7.2.1/src/sundials;/home/borja/sundials/instdir/src/sundials"
  INTERFACE_LINK_LIBRARIES "SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::sunlinsolspfgmr_static
add_library(SUNDIALS::sunlinsolspfgmr_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunlinsolspfgmr_static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "SUNDIALS_STATIC_DEFINE"
  INTERFACE_INCLUDE_DIRECTORIES "/home/borja/sundials/cvode-7.2.1/include;/home/borja/sundials/instdir/include;/home/borja/sundials/cvode-7.2.1/src/sundials;/home/borja/sundials/instdir/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::sunlinsolspfgmr_shared
add_library(SUNDIALS::sunlinsolspfgmr_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::sunlinsolspfgmr_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/borja/sundials/cvode-7.2.1/include;/home/borja/sundials/instdir/include;/home/borja/sundials/cvode-7.2.1/src/sundials;/home/borja/sundials/instdir/src/sundials"
  INTERFACE_LINK_LIBRARIES "SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::sunlinsolspgmr_static
add_library(SUNDIALS::sunlinsolspgmr_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunlinsolspgmr_static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "SUNDIALS_STATIC_DEFINE"
  INTERFACE_INCLUDE_DIRECTORIES "/home/borja/sundials/cvode-7.2.1/include;/home/borja/sundials/instdir/include;/home/borja/sundials/cvode-7.2.1/src/sundials;/home/borja/sundials/instdir/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::sunlinsolspgmr_shared
add_library(SUNDIALS::sunlinsolspgmr_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::sunlinsolspgmr_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/borja/sundials/cvode-7.2.1/include;/home/borja/sundials/instdir/include;/home/borja/sundials/cvode-7.2.1/src/sundials;/home/borja/sundials/instdir/src/sundials"
  INTERFACE_LINK_LIBRARIES "SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::sunlinsolsptfqmr_static
add_library(SUNDIALS::sunlinsolsptfqmr_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunlinsolsptfqmr_static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "SUNDIALS_STATIC_DEFINE"
  INTERFACE_INCLUDE_DIRECTORIES "/home/borja/sundials/cvode-7.2.1/include;/home/borja/sundials/instdir/include;/home/borja/sundials/cvode-7.2.1/src/sundials;/home/borja/sundials/instdir/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::sunlinsolsptfqmr_shared
add_library(SUNDIALS::sunlinsolsptfqmr_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::sunlinsolsptfqmr_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/borja/sundials/cvode-7.2.1/include;/home/borja/sundials/instdir/include;/home/borja/sundials/cvode-7.2.1/src/sundials;/home/borja/sundials/instdir/src/sundials"
  INTERFACE_LINK_LIBRARIES "SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::sunnonlinsolnewton_static
add_library(SUNDIALS::sunnonlinsolnewton_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunnonlinsolnewton_static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "SUNDIALS_STATIC_DEFINE"
  INTERFACE_INCLUDE_DIRECTORIES "/home/borja/sundials/cvode-7.2.1/include;/home/borja/sundials/instdir/include;/home/borja/sundials/cvode-7.2.1/src/sundials;/home/borja/sundials/instdir/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::sunnonlinsolnewton_shared
add_library(SUNDIALS::sunnonlinsolnewton_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::sunnonlinsolnewton_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/borja/sundials/cvode-7.2.1/include;/home/borja/sundials/instdir/include;/home/borja/sundials/cvode-7.2.1/src/sundials;/home/borja/sundials/instdir/src/sundials"
  INTERFACE_LINK_LIBRARIES "SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::sunnonlinsolfixedpoint_static
add_library(SUNDIALS::sunnonlinsolfixedpoint_static STATIC IMPORTED)

set_target_properties(SUNDIALS::sunnonlinsolfixedpoint_static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "SUNDIALS_STATIC_DEFINE"
  INTERFACE_INCLUDE_DIRECTORIES "/home/borja/sundials/cvode-7.2.1/include;/home/borja/sundials/instdir/include;/home/borja/sundials/cvode-7.2.1/src/sundials;/home/borja/sundials/instdir/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::sunnonlinsolfixedpoint_shared
add_library(SUNDIALS::sunnonlinsolfixedpoint_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::sunnonlinsolfixedpoint_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/borja/sundials/cvode-7.2.1/include;/home/borja/sundials/instdir/include;/home/borja/sundials/cvode-7.2.1/src/sundials;/home/borja/sundials/instdir/src/sundials"
  INTERFACE_LINK_LIBRARIES "SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::cvode_static
add_library(SUNDIALS::cvode_static STATIC IMPORTED)

set_target_properties(SUNDIALS::cvode_static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "SUNDIALS_STATIC_DEFINE"
  INTERFACE_INCLUDE_DIRECTORIES "/home/borja/sundials/cvode-7.2.1/include;/home/borja/sundials/instdir/include;/home/borja/sundials/cvode-7.2.1/src/sundials;/home/borja/sundials/instdir/src/sundials"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:-lm>;SUNDIALS::core_shared"
)

# Create imported target SUNDIALS::cvode_shared
add_library(SUNDIALS::cvode_shared SHARED IMPORTED)

set_target_properties(SUNDIALS::cvode_shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/borja/sundials/cvode-7.2.1/include;/home/borja/sundials/instdir/include;/home/borja/sundials/cvode-7.2.1/src/sundials;/home/borja/sundials/instdir/src/sundials"
  INTERFACE_LINK_LIBRARIES "SUNDIALS::core_shared"
)

# Import target "SUNDIALS::core_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::core_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::core_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/borja/sundials/instdir/src/sundials/libsundials_core.a"
  )

# Import target "SUNDIALS::core_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::core_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::core_shared PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/borja/sundials/instdir/src/sundials/libsundials_core.so.7.2.1"
  IMPORTED_SONAME_RELWITHDEBINFO "libsundials_core.so.7"
  )

# Import target "SUNDIALS::nvecserial_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::nvecserial_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::nvecserial_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/borja/sundials/instdir/src/nvector/serial/libsundials_nvecserial.a"
  )

# Import target "SUNDIALS::nvecserial_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::nvecserial_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::nvecserial_shared PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/borja/sundials/instdir/src/nvector/serial/libsundials_nvecserial.so.7.2.1"
  IMPORTED_SONAME_RELWITHDEBINFO "libsundials_nvecserial.so.7"
  )

# Import target "SUNDIALS::nvecmanyvector_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::nvecmanyvector_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::nvecmanyvector_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/borja/sundials/instdir/src/nvector/manyvector/libsundials_nvecmanyvector.a"
  )

# Import target "SUNDIALS::nvecmanyvector_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::nvecmanyvector_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::nvecmanyvector_shared PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/borja/sundials/instdir/src/nvector/manyvector/libsundials_nvecmanyvector.so.7.2.1"
  IMPORTED_SONAME_RELWITHDEBINFO "libsundials_nvecmanyvector.so.7"
  )

# Import target "SUNDIALS::sunmatrixband_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunmatrixband_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunmatrixband_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/borja/sundials/instdir/src/sunmatrix/band/libsundials_sunmatrixband.a"
  )

# Import target "SUNDIALS::sunmatrixband_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunmatrixband_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunmatrixband_shared PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/borja/sundials/instdir/src/sunmatrix/band/libsundials_sunmatrixband.so.5.2.1"
  IMPORTED_SONAME_RELWITHDEBINFO "libsundials_sunmatrixband.so.5"
  )

# Import target "SUNDIALS::sunmatrixdense_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunmatrixdense_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunmatrixdense_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/borja/sundials/instdir/src/sunmatrix/dense/libsundials_sunmatrixdense.a"
  )

# Import target "SUNDIALS::sunmatrixdense_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunmatrixdense_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunmatrixdense_shared PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/borja/sundials/instdir/src/sunmatrix/dense/libsundials_sunmatrixdense.so.5.2.1"
  IMPORTED_SONAME_RELWITHDEBINFO "libsundials_sunmatrixdense.so.5"
  )

# Import target "SUNDIALS::sunmatrixsparse_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunmatrixsparse_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunmatrixsparse_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/borja/sundials/instdir/src/sunmatrix/sparse/libsundials_sunmatrixsparse.a"
  )

# Import target "SUNDIALS::sunmatrixsparse_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunmatrixsparse_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunmatrixsparse_shared PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/borja/sundials/instdir/src/sunmatrix/sparse/libsundials_sunmatrixsparse.so.5.2.1"
  IMPORTED_SONAME_RELWITHDEBINFO "libsundials_sunmatrixsparse.so.5"
  )

# Import target "SUNDIALS::sunlinsolband_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunlinsolband_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunlinsolband_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/borja/sundials/instdir/src/sunlinsol/band/libsundials_sunlinsolband.a"
  )

# Import target "SUNDIALS::sunlinsolband_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunlinsolband_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunlinsolband_shared PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/borja/sundials/instdir/src/sunlinsol/band/libsundials_sunlinsolband.so.5.2.1"
  IMPORTED_SONAME_RELWITHDEBINFO "libsundials_sunlinsolband.so.5"
  )

# Import target "SUNDIALS::sunlinsoldense_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunlinsoldense_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunlinsoldense_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/borja/sundials/instdir/src/sunlinsol/dense/libsundials_sunlinsoldense.a"
  )

# Import target "SUNDIALS::sunlinsoldense_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunlinsoldense_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunlinsoldense_shared PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/borja/sundials/instdir/src/sunlinsol/dense/libsundials_sunlinsoldense.so.5.2.1"
  IMPORTED_SONAME_RELWITHDEBINFO "libsundials_sunlinsoldense.so.5"
  )

# Import target "SUNDIALS::sunlinsolpcg_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunlinsolpcg_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunlinsolpcg_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/borja/sundials/instdir/src/sunlinsol/pcg/libsundials_sunlinsolpcg.a"
  )

# Import target "SUNDIALS::sunlinsolpcg_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunlinsolpcg_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunlinsolpcg_shared PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/borja/sundials/instdir/src/sunlinsol/pcg/libsundials_sunlinsolpcg.so.5.2.1"
  IMPORTED_SONAME_RELWITHDEBINFO "libsundials_sunlinsolpcg.so.5"
  )

# Import target "SUNDIALS::sunlinsolspbcgs_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunlinsolspbcgs_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunlinsolspbcgs_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/borja/sundials/instdir/src/sunlinsol/spbcgs/libsundials_sunlinsolspbcgs.a"
  )

# Import target "SUNDIALS::sunlinsolspbcgs_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunlinsolspbcgs_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunlinsolspbcgs_shared PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/borja/sundials/instdir/src/sunlinsol/spbcgs/libsundials_sunlinsolspbcgs.so.5.2.1"
  IMPORTED_SONAME_RELWITHDEBINFO "libsundials_sunlinsolspbcgs.so.5"
  )

# Import target "SUNDIALS::sunlinsolspfgmr_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunlinsolspfgmr_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunlinsolspfgmr_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/borja/sundials/instdir/src/sunlinsol/spfgmr/libsundials_sunlinsolspfgmr.a"
  )

# Import target "SUNDIALS::sunlinsolspfgmr_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunlinsolspfgmr_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunlinsolspfgmr_shared PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/borja/sundials/instdir/src/sunlinsol/spfgmr/libsundials_sunlinsolspfgmr.so.5.2.1"
  IMPORTED_SONAME_RELWITHDEBINFO "libsundials_sunlinsolspfgmr.so.5"
  )

# Import target "SUNDIALS::sunlinsolspgmr_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunlinsolspgmr_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunlinsolspgmr_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/borja/sundials/instdir/src/sunlinsol/spgmr/libsundials_sunlinsolspgmr.a"
  )

# Import target "SUNDIALS::sunlinsolspgmr_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunlinsolspgmr_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunlinsolspgmr_shared PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/borja/sundials/instdir/src/sunlinsol/spgmr/libsundials_sunlinsolspgmr.so.5.2.1"
  IMPORTED_SONAME_RELWITHDEBINFO "libsundials_sunlinsolspgmr.so.5"
  )

# Import target "SUNDIALS::sunlinsolsptfqmr_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunlinsolsptfqmr_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunlinsolsptfqmr_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/borja/sundials/instdir/src/sunlinsol/sptfqmr/libsundials_sunlinsolsptfqmr.a"
  )

# Import target "SUNDIALS::sunlinsolsptfqmr_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunlinsolsptfqmr_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunlinsolsptfqmr_shared PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/borja/sundials/instdir/src/sunlinsol/sptfqmr/libsundials_sunlinsolsptfqmr.so.5.2.1"
  IMPORTED_SONAME_RELWITHDEBINFO "libsundials_sunlinsolsptfqmr.so.5"
  )

# Import target "SUNDIALS::sunnonlinsolnewton_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunnonlinsolnewton_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunnonlinsolnewton_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/borja/sundials/instdir/src/sunnonlinsol/newton/libsundials_sunnonlinsolnewton.a"
  )

# Import target "SUNDIALS::sunnonlinsolnewton_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunnonlinsolnewton_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunnonlinsolnewton_shared PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/borja/sundials/instdir/src/sunnonlinsol/newton/libsundials_sunnonlinsolnewton.so.4.2.1"
  IMPORTED_SONAME_RELWITHDEBINFO "libsundials_sunnonlinsolnewton.so.4"
  )

# Import target "SUNDIALS::sunnonlinsolfixedpoint_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunnonlinsolfixedpoint_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunnonlinsolfixedpoint_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/borja/sundials/instdir/src/sunnonlinsol/fixedpoint/libsundials_sunnonlinsolfixedpoint.a"
  )

# Import target "SUNDIALS::sunnonlinsolfixedpoint_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::sunnonlinsolfixedpoint_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::sunnonlinsolfixedpoint_shared PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/borja/sundials/instdir/src/sunnonlinsol/fixedpoint/libsundials_sunnonlinsolfixedpoint.so.4.2.1"
  IMPORTED_SONAME_RELWITHDEBINFO "libsundials_sunnonlinsolfixedpoint.so.4"
  )

# Import target "SUNDIALS::cvode_static" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::cvode_static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::cvode_static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/borja/sundials/instdir/src/cvode/libsundials_cvode.a"
  )

# Import target "SUNDIALS::cvode_shared" for configuration "RelWithDebInfo"
set_property(TARGET SUNDIALS::cvode_shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SUNDIALS::cvode_shared PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/home/borja/sundials/instdir/src/cvode/libsundials_cvode.so.7.2.1"
  IMPORTED_SONAME_RELWITHDEBINFO "libsundials_cvode.so.7"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
