%% run_SIR_CUQDyn1Plus_HybridCov.m
% --------------------------------------------------------
% BENCHMARK: NON-LINEAR SIR MODEL  —  CUQDyn1_Plus_HybridCov
% --------------------------------------------------------
% Observed:   State 2 (Infected)
% Unobserved: State 1 (Susceptible), State 3 (Recovered)
%
% Identical to run_SIR_CUQDyn1Plus.m except:
%   - CUQDyn1_Plus        replaced by CUQDyn1_Plus_HybridCov
%   - resultDir name      updated accordingly
%   - MCMC block omitted  (use run_SIR_CUQDyn1Plus.m for MCMC comparison)
%   - Additional diagnostic figures specific to the hybrid method:
%       Fig A — FIM vs LOO vs Hybrid marginal std devs
%       Fig B — LOO correlation matrix R_LOO
%       Fig C — FIM vs Hybrid prediction bands (decoupled subplots)
%

clear; close all; clc;
addpath(genpath('../../'));

% ====================================================================
% 1. PROBLEM CONFIGURATION
% ====================================================================
fprintf('--- 1. Problem configuration ---\n');

dynamics_handle = @prob_mod_dynamics_SIR;
cost_handle     = @prob_mod_cost_SIR;

nstates     = 3;
n_params    = 2;
param_names = {'beta','gamma'};

true_params = [0.002, 0.5];

guess_params = [0.001, 0.2];
lb_params    = [0.0001, 0.01];
ub_params    = [0.01,   2.0];
alp          = 0.05;   % nominal 1-2*alp = 90% two-sided coverage

% Optimiser / integration defaults
opts = cuqdyn_default_options(n_params);
opts.uq.alp = alp;
opts.ode.RelTol = 1e-8;
opts.ode.AbsTol = 1e-8;
cuqdyn_set_ode_options(opts.ode);
meigo_opts = opts.meigo;

% ====================================================================
% 2. LOAD SYNTHETIC DATA  (generated by run_SIR_CUQDyn1Plus.m)
% ====================================================================
fprintf('--- 2. Loading synthetic epidemic data from CSV ---\n');

dataDir = fullfile(fileparts(mfilename('fullpath')), 'data');
data_file_name = 'sir_data.csv';
[times, all_state_data, initial_values_all_states, observed_data, observed_idx] = ...
    loadStateData(dataDir, data_file_name, nstates);
unobs_idx      = find(~ismember(1:nstates, observed_idx));   % [1, 3]

[ode_options, ~] = cuqdyn_get_ode_options();
[~, Y_true_for_sigma] = ode15s(@(t,y) dynamics_handle(t,y,true_params), ...
    times, initial_values_all_states, ode_options);
noise_pct = 10;
opts.cost.residual_model = 'known_sigma';
opts.cost.sigma = (noise_pct/100) * mean(Y_true_for_sigma(2:end, observed_idx));
opts.cost.sigma_is_known = true;
meigo_opts.cost_opts = opts.cost;

% ====================================================================
% 3. RESULTS DIRECTORY
% ====================================================================
nowTime   = datetime('now');
timestamp = string(nowTime,'yyyy-MM-dd_HH-mm-ss');
resultDir = "Results_SIR_HybridCov_" + timestamp;
mkdir(resultDir);

% ====================================================================
% 4. RUN CUQDyn1_Plus_HybridCov
% ====================================================================
fprintf('--- 4. Running CUQDyn1_Plus_HybridCov ---\n');

results = CUQDyn1_Plus_HybridCov( ...
    cost_handle, dynamics_handle, nstates, n_params, ...
    guess_params, lb_params, ub_params, alp, ...
    times, all_state_data, initial_values_all_states, ...
    observed_data, observed_idx, resultDir, meigo_opts);

% Standard toolbox outputs
plot_hybrid_uq(results, resultDir);
save_results_to_excel_detailed(results, resultDir, true_params, ...
                                guess_params, lb_params, ub_params, data_file_name);

% Parameter recovery summary
print_param_recovery(results, true_params, param_names, alp);

% --- Trajectory prediction error summary --
save_trajectory_nrmse_tables(results, resultDir);


% ====================================================================
% 5. RECOMPUTE FIM-ONLY BANDS FOR COMPARISON
% ====================================================================
fprintf('\n--- 5. Computing FIM-only bands for comparison ---\n');

[UQ_l_fim, UQ_u_fim, ~, ~] = fast_compute_hybrid_uncertainty( ...
    results.media_tot, observed_data, observed_idx, ...
    initial_values_all_states, times, results.parameters_init, ...
    nstates, n_params, length(times), ...
    results.UQ_lower(:, observed_idx), results.UQ_upper(:, observed_idx), ...
    alp, dynamics_handle, @ODE_solve, results.options.cost, results.options.ode);

% ====================================================================
% 6. HYBRID-SPECIFIC DIAGNOSTIC FIGURES
% ====================================================================
fprintf('--- 6. Plotting hybrid diagnostics ---\n');

% True noise-free trajectory (needed for comparison panels in Fig C)
[~, Y_true] = ode15s(@(t,y) dynamics_handle(t,y,true_params), ...
                     times, initial_values_all_states, ...
                     cuqdyn_get_ode_options());

% --- Fig A: Marginal std dev comparison ---
fig_a = figure('Color','w','Position',[100 100 600 340]);
hold on; grid on;
x_pos = 1:n_params;
bw    = 0.25;
bar(x_pos - bw, results.D_fim',                        bw, 'FaceColor',[0.85 0.2 0.2],'FaceAlpha',0.8,'DisplayName','FIM');
bar(x_pos,      sqrt(diag(results.Cov_p_loo))',         bw, 'FaceColor',[0.2 0.3 0.85],'FaceAlpha',0.8,'DisplayName','LOO');
bar(x_pos + bw, sqrt(diag(results.Cov_p))',             bw, 'FaceColor',[0.1 0.65 0.2],'FaceAlpha',0.8,'DisplayName','Hybrid');
set(gca,'XTick',x_pos,'XTickLabel',param_names,'FontSize',12);
ylabel('Marginal std dev','FontSize',12);
title({'Parameter marginal std devs: FIM vs LOO vs Hybrid', ...
       'Hybrid = FIM scale by construction'},'FontSize',11,'FontWeight','bold');
legend('FontSize',10,'Location','best');
set(findall(fig_a,'Type','axes'),'Color','w');   % force light axes background
savefig_png(fig_a, fullfile(resultDir,'diag_marginal_stddev'));

% --- Fig B: LOO correlation matrix ---
fig_b = figure('Color','w','Position',[200 200 420 380]);
imagesc(results.R_loo); colorbar; caxis([-1 1]);
colormap(redblue_cmap(64));
set(gca,'XTick',1:n_params,'XTickLabel',param_names, ...
        'YTick',1:n_params,'YTickLabel',param_names,'FontSize',13);
for ri = 1:n_params
    for ci = 1:n_params
        text(ci, ri, sprintf('%.3f', results.R_loo(ri,ci)), ...
             'HorizontalAlignment','center','FontSize',12,'Color','k');
    end
end
title('LOO correlation matrix R_{LOO}','FontSize',12,'FontWeight','bold');
savefig_png(fig_b, fullfile(resultDir,'diag_loo_correlation'));

% --- Fig C: Decoupled FIM vs Hybrid band comparison (one figure per
%            unobserved state, four-panel layout matching LV diagnostic)
for j = unobs_idx
    w_fim = UQ_u_fim(:,j) - UQ_l_fim(:,j);
    w_hyb = results.UQ_upper(:,j) - results.UQ_lower(:,j);
    state_name = get_state_name(j);

    fig_c = figure('Color','w','Position',[100 100 1100 820]);

    % Panel 1: FIM band
    ax1 = subplot(2,2,1); hold on; grid on;
    fill([times; flipud(times)], ...
         [max(0,UQ_l_fim(:,j)); flipud(UQ_u_fim(:,j))], ...
         [0.85 0.2 0.2],'FaceAlpha',0.30,'EdgeColor','none');
    plot(times, UQ_u_fim(:,j),'r--','LineWidth',1);
    plot(times, max(0,UQ_l_fim(:,j)),'r--','LineWidth',1);
    plot(times, results.media_tot(:,j),'k-','LineWidth',2,'DisplayName','Best fit');
    plot(times, Y_true(:,j),'g-','LineWidth',1.5,'DisplayName','True');
    xlabel('Time (days)','FontSize',11); ylabel('Population','FontSize',11);
    title(sprintf('FIM 90%% CI — %s  (mean width = %.2f)', state_name, mean(w_fim(2:end))), ...
          'FontSize',11,'FontWeight','bold');
    legend('FIM band','','Best fit','True','Location','best','FontSize',9);

    % Panel 2: Hybrid band (same y-scale)
    ax2 = subplot(2,2,2); hold on; grid on;
    fill([times; flipud(times)], ...
         [max(0,results.UQ_lower(:,j)); flipud(results.UQ_upper(:,j))], ...
         [0.1 0.65 0.2],'FaceAlpha',0.30,'EdgeColor','none');
    plot(times, results.UQ_upper(:,j),'--','Color',[0.1 0.65 0.2],'LineWidth',1);
    plot(times, max(0,results.UQ_lower(:,j)),'--','Color',[0.1 0.65 0.2],'LineWidth',1);
    plot(times, results.media_tot(:,j),'k-','LineWidth',2,'DisplayName','Best fit');
    plot(times, Y_true(:,j),'g-','LineWidth',1.5,'DisplayName','True');
    xlabel('Time (days)','FontSize',11); ylabel('Population','FontSize',11);
    title(sprintf('Hybrid 90%% CI — %s  (mean width = %.2f)', state_name, mean(w_hyb(2:end))), ...
          'FontSize',11,'FontWeight','bold');
    legend('Hybrid band','','Best fit','True','Location','best','FontSize',9);
    linkaxes([ax1 ax2],'xy');

    % Panel 3: Band width over time
    subplot(2,2,3); hold on; grid on;
    plot(times, w_fim, '-s','Color',[0.85 0.2 0.2],'LineWidth',2,'MarkerSize',4,'DisplayName','FIM');
    plot(times, w_hyb, '-^','Color',[0.1 0.65 0.2],'LineWidth',2,'MarkerSize',4,'DisplayName','Hybrid');
    xlabel('Time (days)','FontSize',11); ylabel('Band width','FontSize',11);
    title('Band width over time','FontSize',11,'FontWeight','bold');
    legend('FontSize',10,'Location','best');

    % Panel 4: Hybrid / FIM width ratio
    subplot(2,2,4); hold on; grid on;
    ratio_w = w_hyb ./ max(w_fim, 1e-6);
    plot(times, ratio_w,'k-','LineWidth',2);
    yline(1,'r--','LineWidth',1.5);
    xlabel('Time (days)','FontSize',11);
    ylabel('Width ratio Hybrid / FIM','FontSize',11);
    title({'Hybrid / FIM width ratio', ...
           '>1: Hybrid wider  |  <1: Hybrid narrower'}, ...
          'FontSize',11,'FontWeight','bold');
    ylim([0, max(ratio_w)*1.1 + 0.05]);

    sgtitle(sprintf('State %d (%s): FIM vs Hybrid band comparison', j, state_name), ...
            'FontSize',13,'FontWeight','bold');

    set(findall(fig_c,'Type','axes'),'Color','w');   % force light axes background
    savefig_png(fig_c, fullfile(resultDir, sprintf('diag_band_comparison_state%d',j)));
    close(fig_c);
end

fprintf('\nAll results saved to: %s\n', resultDir);

% ====================================================================
% LOCAL FUNCTIONS
% ====================================================================
function name = get_state_name(j)
    names = {'Susceptible','Infected','Recovered'};
    if j <= numel(names)
        name = names{j};
    else
        name = sprintf('State %d', j);
    end
end

function cmap = redblue_cmap(n)
    half = floor(n/2);
    r = [ones(1,half),      linspace(1,0,n-half)];
    g = [linspace(0,1,half),linspace(1,0,n-half)];
    b = [linspace(0,1,half),ones(1,n-half)];
    cmap = [r(:), g(:), b(:)];
end
