[package]
name = "cuqdyn-rs"
version = "0.1.0"
edition = "2018"

[dependencies]
fee = { version = "0.2.2" }
getset = { version = "0.1.5" }
serde = { version = "*" }
serde-xml-rs = { version = "0.8.1"}

[dev-dependencies]
criterion = { version = "0.5.1" }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
# strip = "symbols"

[[bench]]
name = "eval_f_exprs_bench"
harness = false

[lib]
name = "cuqdyn_rs"
crate-type = ["cdylib", "lib"]
