function generated = cuqdyn_generate_data_script(problem, outputDir, varargin)
%CUQDYN_GENERATE_DATA_SCRIPT Generate a readable synthetic-data script.
%
% The generated script calls cuqdyn_generate_synthetic_data(problem, ...)
% rather than duplicating the full data-generation implementation.

opts = parseOptions(varargin{:});
problem = cuqdyn_validate_problem(problem);

if nargin < 2 || isempty(outputDir)
    outputDir = pwd;
end
if isstring(outputDir), outputDir = char(outputDir); end
if ~exist(outputDir, 'dir') && ~opts.DryRun
    mkdir(outputDir);
end

scriptName = sprintf('generateSyntheticData_%s.m', char(problem.name));
scriptPath = fullfile(outputDir, scriptName);
scriptText = buildScriptText(problem);

if ~opts.DryRun
    writeTextFile(scriptPath, scriptText, opts.Overwrite);
end

generated = struct();
generated.scriptFile = string(scriptPath);
generated.scriptText = string(scriptText);
end

function opts = parseOptions(varargin)
opts = struct();
opts.Overwrite = false;
opts.DryRun = false;

if mod(numel(varargin), 2) ~= 0
    error('cuqdyn_generate_data_script:InvalidInputs', ...
        'Options must be supplied as name-value pairs.');
end

for i = 1:2:numel(varargin)
    name = validatestring(varargin{i}, {'Overwrite', 'DryRun'});
    opts.(name) = varargin{i+1};
end
end

function txt = buildScriptText(problem)
name = char(problem.name);
defineName = sprintf('define_problem_%s', name);
dynamicsName = sprintf('prob_mod_dynamics_%s', name);

lines = strings(0, 1);
lines(end+1) = sprintf('%% generateSyntheticData_%s.m', name);
lines(end+1) = sprintf('%% Generated by cuqdyn_generate_data_script from %s.m.', defineName);
lines(end+1) = '';
lines(end+1) = 'clear; close all; clc;';
lines(end+1) = '';
lines(end+1) = 'scriptDir = fileparts(mfilename(''fullpath''));';
lines(end+1) = 'repoRoot = findRepoRoot(scriptDir);';
lines(end+1) = 'addpath(genpath(repoRoot));';
lines(end+1) = '';
lines(end+1) = sprintf('problem = %s();', defineName);
lines(end+1) = 'cuqdyn_validate_problem(problem);';
lines(end+1) = '';
lines(end+1) = '% Generate local problem modules before simulating data.';
lines(end+1) = 'generatedModuleDir = fullfile(fileparts(scriptDir), ''generated_problem'');';
lines(end+1) = 'cuqdyn_generate_problem_files(problem, generatedModuleDir, ''Overwrite'', true);';
lines(end+1) = 'addpath(generatedModuleDir, ''-begin'');';
lines(end+1) = '';
lines(end+1) = 'exampleDir = fileparts(scriptDir);';
lines(end+1) = sprintf('out = cuqdyn_generate_synthetic_data(problem, ''BaseDir'', exampleDir, ''DynamicsHandle'', @%s);', dynamicsName);
lines(end+1) = 'disp(out.outputCsv);';
lines(end+1) = '';
lines(end+1) = 'function repoRoot = findRepoRoot(startDir)';
lines(end+1) = 'repoRoot = startDir;';
lines(end+1) = 'while ~exist(fullfile(repoRoot, ''setPath_CUQDyn1_Plus.m''), ''file'')';
lines(end+1) = '    parentDir = fileparts(repoRoot);';
lines(end+1) = '    if strcmp(parentDir, repoRoot)';
lines(end+1) = '        error(''generateSyntheticData:RepoRootNotFound'', ...';
lines(end+1) = '            ''Could not locate setPath_CUQDyn1_Plus.m above %s.'', startDir);';
lines(end+1) = '    end';
lines(end+1) = '    repoRoot = parentDir;';
lines(end+1) = 'end';
lines(end+1) = 'end';

txt = char(join(lines, newline));
end

function writeTextFile(filePath, txt, overwrite)
if exist(filePath, 'file') && ~overwrite
    error('cuqdyn_generate_data_script:FileExists', ...
        'File already exists: %s. Use ''Overwrite'', true to replace it.', filePath);
end

fid = fopen(filePath, 'w');
if fid < 0
    error('cuqdyn_generate_data_script:FileOpenFailed', ...
        'Could not open file for writing: %s.', filePath);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '%s\n', txt);
end
