function generated = cuqdyn_generate_problem_files(problem, outputDir, varargin)
%CUQDYN_GENERATE_PROBLEM_FILES Generate legacy CUQDyn problem module files.
%
% generated = cuqdyn_generate_problem_files(problem, outputDir) validates a
% high-level problem struct and writes legacy-compatible MATLAB functions:
%
%   prob_mod_dynamics_<problem.name>.m
%   prob_mod_cost_<problem.name>.m
%
% The generated cost file is a compatibility wrapper around
% prob_mod_cost_Generic, so existing examples can keep using the usual
% problem-specific cost function handle. The generated dynamics file preserves
% complex-step compatibility by allocating derivatives with zeros(...,'like',y).
%
% Name-value options:
%   'Overwrite'  replace existing files (default false).
%   'DryRun'     return generated text without writing files (default false).

opts = parseOptions(varargin{:});
problem = cuqdyn_validate_problem(problem);

if nargin < 2 || isempty(outputDir)
    outputDir = pwd;
end
if isstring(outputDir), outputDir = char(outputDir); end
if ~ischar(outputDir)
    error('cuqdyn_generate_problem_files:InvalidOutputDir', ...
        'outputDir must be a character vector or string scalar.');
end

if ~exist(outputDir, 'dir') && ~opts.DryRun
    mkdir(outputDir);
end

dynamicsName = sprintf('prob_mod_dynamics_%s', char(problem.name));
costName = sprintf('prob_mod_cost_%s', char(problem.name));
dynamicsPath = fullfile(outputDir, [dynamicsName '.m']);
costPath = fullfile(outputDir, [costName '.m']);

dynamicsText = buildDynamicsText(problem, dynamicsName);
costText = buildCostText(problem, costName);

if ~opts.DryRun
    writeTextFile(dynamicsPath, dynamicsText, opts.Overwrite);
    writeTextFile(costPath, costText, opts.Overwrite);
end

generated = struct();
generated.problem = problem;
generated.outputDir = string(outputDir);
generated.dynamicsFunction = string(dynamicsName);
generated.costFunction = string(costName);
generated.dynamicsFile = string(dynamicsPath);
generated.costFile = string(costPath);
generated.dynamicsText = string(dynamicsText);
generated.costText = string(costText);
end

function opts = parseOptions(varargin)
opts = struct();
opts.Overwrite = false;
opts.DryRun = false;

if mod(numel(varargin), 2) ~= 0
    error('cuqdyn_generate_problem_files:InvalidInputs', ...
        'Options must be supplied as name-value pairs.');
end

for i = 1:2:numel(varargin)
    name = validatestring(varargin{i}, {'Overwrite', 'DryRun'});
    opts.(name) = varargin{i+1};
end
end

function txt = buildDynamicsText(problem, functionName)
nStates = numel(problem.states);
nParams = numel(problem.parameters);

lines = strings(0, 1);
lines(end+1) = sprintf('function dy = %s(t, y, p) %%#ok<INUSD>', functionName);
lines(end+1) = sprintf('%%%s Generated CUQDyn dynamics function.', upper(functionName));
lines(end+1) = '% Generated by cuqdyn_generate_problem_files.';
lines(end+1) = '%';
lines(end+1) = '% States:';
for i = 1:nStates
    lines(end+1) = sprintf('%%   y(%d) = %s', i, problem.states(i)); %#ok<AGROW>
end
lines(end+1) = '% Parameters:';
for i = 1:nParams
    lines(end+1) = sprintf('%%   p(%d) = %s', i, problem.parameters(i)); %#ok<AGROW>
end
lines(end+1) = '';
lines(end+1) = sprintf('dy = zeros(%d, 1, ''like'', y);', nStates);
lines(end+1) = '';
for i = 1:nStates
    lines(end+1) = sprintf('%s = y(%d);', problem.states(i), i); %#ok<AGROW>
end
if nStates > 0 && nParams > 0
    lines(end+1) = '';
end
for i = 1:nParams
    lines(end+1) = sprintf('%s = p(%d);', problem.parameters(i), i); %#ok<AGROW>
end
lines(end+1) = '';
for i = 1:nStates
    lines(end+1) = sprintf('dy(%d) = %s;', i, problem.odes(i)); %#ok<AGROW>
end
lines(end+1) = 'end';

txt = join(lines, newline);
txt = char(txt);
end

function txt = buildCostText(problem, functionName)
lines = strings(0, 1);
lines(end+1) = sprintf('function [J, g, R] = %s(x, texp, yexp, observed_idx, dynamics_func_handle, initial_values_all_states, ode_opts, cost_opts)', functionName);
lines(end+1) = sprintf('%%%s Generated CUQDyn cost wrapper for %s.', upper(functionName), problem.name);
lines(end+1) = '% Generated by cuqdyn_generate_problem_files.';
lines(end+1) = '';
lines(end+1) = 'if nargin < 7';
lines(end+1) = '    ode_opts = [];';
lines(end+1) = 'end';
lines(end+1) = 'if nargin < 8';
lines(end+1) = '    cost_opts = struct();';
lines(end+1) = 'end';
lines(end+1) = '[J, g, R] = prob_mod_cost_Generic(x, texp, yexp, observed_idx, dynamics_func_handle, initial_values_all_states, ode_opts, cost_opts);';
lines(end+1) = 'end';

txt = join(lines, newline);
txt = char(txt);
end

function writeTextFile(filePath, txt, overwrite)
if exist(filePath, 'file') && ~overwrite
    error('cuqdyn_generate_problem_files:FileExists', ...
        'File already exists: %s. Use ''Overwrite'', true to replace it.', filePath);
end

fid = fopen(filePath, 'w');
if fid < 0
    error('cuqdyn_generate_problem_files:FileOpenFailed', ...
        'Could not open file for writing: %s.', filePath);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '%s\n', txt);
end
