name: Run Tests

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
              libhdf5-dev \
              libgsl-dev

      - name: Make test.sh executable
        run: |
          chmod +x ./test.sh
          chmod +x ./build.sh

      - name: Run test script
        run: ./build.sh && ./test.sh
